### ISSUE TITLE
Add support for alternative input/output linking

### ISSUE THREAD

**Issue by eddybl** [epics-modules/opcua#155]
**Is your feature request related to a problem? Please describe.**

As discussed with @ralphlange he wanted to include the option to use the same syntax for linking to the OPCUA records as it is used in our device support (which is bascially 1:1 copy of the address as shown in an UPCA UA client, but requires quote escaping):
https://github.com/KIT-IBPT/epics-open62541

**Comment by eddybl** [comment]
@ralphlange do you think this is something which will happen realistically over the next 2-3 months?

If not, I would probably start "testing" this driver in its current state. It will be less efficient, as I cannot just replace the `DTYP` field.

As far as I can tell the differences are small:

```
#opcua driver
field(INP, "@<name> ns=<namespace>;s=<identifierString> [<option>=<value>...]")

#open62541 driver
field(INP, "@<name>  [<options>] <namespace>;<identifierString> [<data type>] ")
```

In the case of no additional options, as far as I can see the main difference is:

```
#opcua driver
ns=<namespace>;s=<identifierString>")

#open62541 driver
<namespace>;<identifierString>")
```

so the opcua driver requires the additional `ns=` and `s=`

Then of course there are differences in the optional arguments and subscription handling, but at least in our case we probably don't use them much and around 80% of records are without optional arguments

**Comment by ralphlange** [comment]
It's pretty high up on my list, and we just seem to be entering a "hot phase" of merging and adding stuff.
Give me two weeks - if I'm not getting it in by then, please go ahead.

**Comment by eddybl** [comment]
yeah, I noticed ;)

ok, in that timeframe I wouldn't be able to do much anyway

**Comment by ralphlange** [comment]
This feature has been added in my fork at
https://github.com/ralphlange/opcua/tree/feature/epics-open62541-compat

I don't expect this to be added permanently to the official module - closing this ticket.
